packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@nestjs/core": true
  "@next/swc-darwin-arm64": true
  "@next/swc-darwin-x64": true
  "@next/swc-linux-arm64-gnu": true
  "@next/swc-linux-arm64-musl": true
  "@next/swc-linux-x64-gnu": true
  "@next/swc-linux-x64-musl": true
  "@next/swc-win32-arm64-msvc": true
  "@next/swc-win32-x64-msvc": true
  "@prisma/client": true
  "@prisma/engines": true
  napi-postinstall: true
  prisma: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "esbuild"
  - "@next/swc-darwin-arm64"
  - "@next/swc-darwin-x64"
  - "@next/swc-linux-arm64-gnu"
  - "@next/swc-linux-arm64-musl"
  - "@next/swc-linux-x64-gnu"
  - "@next/swc-linux-x64-musl"
  - "@next/swc-win32-arm64-msvc"
  - "@next/swc-win32-x64-msvc"
  - "@prisma/client"
  - "@prisma/engines"
  - "napi-postinstall"
  - "prisma"
  - "sharp"
  - "unrs-resolver"
