"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MODULE_PERMISSIONS = exports.PERMISSIONS = void 0;
exports.PERMISSIONS = {
    PLATFORM_READ: "platform.read",
    PLATFORM_MANAGE: "platform.manage",
    IDENTITY_READ: "identity.read",
    IDENTITY_MANAGE: "identity.manage",
    INVENTORY_READ: "inventory.read",
    INVENTORY_MANAGE: "inventory.manage",
    POULTRY_READ: "poultry.read",
    POULTRY_MANAGE: "poultry.manage",
    POULTRY_RECORD: "poultry.record",
    FEED_READ: "feed.read",
    FEED_MANAGE: "feed.manage",
    SOYA_READ: "soya.read",
    SOYA_MANAGE: "soya.manage",
    FINANCE_READ: "finance.read",
    FINANCE_MANAGE: "finance.manage",
    SALES_READ: "sales.read",
    SALES_MANAGE: "sales.manage",
    PROCUREMENT_READ: "procurement.read",
    PROCUREMENT_MANAGE: "procurement.manage",
    MARKET_PLANNING_READ: "market-planning.read",
    MARKET_PLANNING_MANAGE: "market-planning.manage",
    HR_READ: "hr.read",
    HR_MANAGE: "hr.manage",
    MAINTENANCE_READ: "maintenance.read",
    MAINTENANCE_MANAGE: "maintenance.manage",
    QUALITY_READ: "quality.read",
    QUALITY_MANAGE: "quality.manage",
    HEALTH_READ: "health.read",
    HEALTH_MANAGE: "health.manage",
    REPORTS_EXPORT: "reports.export",
    SETTINGS_MANAGE: "settings.manage",
    AUDIT_READ: "audit.read",
    AI_READ: "ai.read",
    ALERTS_READ: "alerts.read",
    ALERTS_MANAGE: "alerts.manage",
    QUICKBOOKS_READ: "quickbooks.read",
    QUICKBOOKS_MANAGE: "quickbooks.manage",
    EXECUTIVE_READ: "executive.read"
};
exports.MODULE_PERMISSIONS = {
    Platform: [exports.PERMISSIONS.PLATFORM_READ, exports.PERMISSIONS.PLATFORM_MANAGE],
    Identity: [exports.PERMISSIONS.IDENTITY_READ, exports.PERMISSIONS.IDENTITY_MANAGE],
    Inventory: [exports.PERMISSIONS.INVENTORY_READ, exports.PERMISSIONS.INVENTORY_MANAGE],
    Poultry: [exports.PERMISSIONS.POULTRY_READ, exports.PERMISSIONS.POULTRY_MANAGE, exports.PERMISSIONS.POULTRY_RECORD],
    "Feed Production": [exports.PERMISSIONS.FEED_READ, exports.PERMISSIONS.FEED_MANAGE],
    "Soya Processing": [exports.PERMISSIONS.SOYA_READ, exports.PERMISSIONS.SOYA_MANAGE],
    Finance: [exports.PERMISSIONS.FINANCE_READ, exports.PERMISSIONS.FINANCE_MANAGE],
    Sales: [exports.PERMISSIONS.SALES_READ, exports.PERMISSIONS.SALES_MANAGE],
    Procurement: [exports.PERMISSIONS.PROCUREMENT_READ, exports.PERMISSIONS.PROCUREMENT_MANAGE],
    "Market Planning": [exports.PERMISSIONS.MARKET_PLANNING_READ, exports.PERMISSIONS.MARKET_PLANNING_MANAGE],
    HR: [exports.PERMISSIONS.HR_READ, exports.PERMISSIONS.HR_MANAGE],
    Maintenance: [exports.PERMISSIONS.MAINTENANCE_READ, exports.PERMISSIONS.MAINTENANCE_MANAGE],
    "Quality Control": [exports.PERMISSIONS.QUALITY_READ, exports.PERMISSIONS.QUALITY_MANAGE],
    "Vet and Health": [exports.PERMISSIONS.HEALTH_READ, exports.PERMISSIONS.HEALTH_MANAGE],
    Reports: [exports.PERMISSIONS.REPORTS_EXPORT],
    Settings: [exports.PERMISSIONS.SETTINGS_MANAGE],
    Audit: [exports.PERMISSIONS.AUDIT_READ],
    "AI Assistant": [exports.PERMISSIONS.AI_READ],
    "Alerts": [exports.PERMISSIONS.ALERTS_READ, exports.PERMISSIONS.ALERTS_MANAGE],
    "QuickBooks": [exports.PERMISSIONS.QUICKBOOKS_READ, exports.PERMISSIONS.QUICKBOOKS_MANAGE],
    "Executive": [exports.PERMISSIONS.EXECUTIVE_READ]
};
