export const PERMISSIONS = {
  PLATFORM_READ: "platform.read",
  PLATFORM_MANAGE: "platform.manage",
  IDENTITY_READ: "identity.read",
  IDENTITY_MANAGE: "identity.manage",
  INVENTORY_READ: "inventory.read",
  INVENTORY_MANAGE: "inventory.manage",
  POULTRY_READ: "poultry.read",
  POULTRY_MANAGE: "poultry.manage",
  POULTRY_RECORD: "poultry.record",
  FEED_READ: "feed.read",
  FEED_MANAGE: "feed.manage",
  SOYA_READ: "soya.read",
  SOYA_MANAGE: "soya.manage",
  FINANCE_READ: "finance.read",
  FINANCE_MANAGE: "finance.manage",
  SALES_READ: "sales.read",
  SALES_MANAGE: "sales.manage",
  PROCUREMENT_READ: "procurement.read",
  PROCUREMENT_MANAGE: "procurement.manage",
  MARKET_PLANNING_READ: "market-planning.read",
  MARKET_PLANNING_MANAGE: "market-planning.manage",
  HR_READ: "hr.read",
  HR_MANAGE: "hr.manage",
  MAINTENANCE_READ: "maintenance.read",
  MAINTENANCE_MANAGE: "maintenance.manage",
  QUALITY_READ: "quality.read",
  QUALITY_MANAGE: "quality.manage",
  HEALTH_READ: "health.read",
  HEALTH_MANAGE: "health.manage",
  REPORTS_EXPORT: "reports.export",
  SETTINGS_MANAGE: "settings.manage",
  AUDIT_READ: "audit.read",
  AI_READ: "ai.read",
  ALERTS_READ: "alerts.read",
  ALERTS_MANAGE: "alerts.manage",
  QUICKBOOKS_READ: "quickbooks.read",
  QUICKBOOKS_MANAGE: "quickbooks.manage",
  EXECUTIVE_READ: "executive.read"
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const MODULE_PERMISSIONS: Record<string, PermissionKey[]> = {
  Platform: [PERMISSIONS.PLATFORM_READ, PERMISSIONS.PLATFORM_MANAGE],
  Identity: [PERMISSIONS.IDENTITY_READ, PERMISSIONS.IDENTITY_MANAGE],
  Inventory: [PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_MANAGE],
  Poultry: [PERMISSIONS.POULTRY_READ, PERMISSIONS.POULTRY_MANAGE, PERMISSIONS.POULTRY_RECORD],
  "Feed Production": [PERMISSIONS.FEED_READ, PERMISSIONS.FEED_MANAGE],
  "Soya Processing": [PERMISSIONS.SOYA_READ, PERMISSIONS.SOYA_MANAGE],
  Finance: [PERMISSIONS.FINANCE_READ, PERMISSIONS.FINANCE_MANAGE],
  Sales: [PERMISSIONS.SALES_READ, PERMISSIONS.SALES_MANAGE],
  Procurement: [PERMISSIONS.PROCUREMENT_READ, PERMISSIONS.PROCUREMENT_MANAGE],
  "Market Planning": [PERMISSIONS.MARKET_PLANNING_READ, PERMISSIONS.MARKET_PLANNING_MANAGE],
  HR: [PERMISSIONS.HR_READ, PERMISSIONS.HR_MANAGE],
  Maintenance: [PERMISSIONS.MAINTENANCE_READ, PERMISSIONS.MAINTENANCE_MANAGE],
  "Quality Control": [PERMISSIONS.QUALITY_READ, PERMISSIONS.QUALITY_MANAGE],
  "Vet and Health": [PERMISSIONS.HEALTH_READ, PERMISSIONS.HEALTH_MANAGE],
  Reports: [PERMISSIONS.REPORTS_EXPORT],
  Settings: [PERMISSIONS.SETTINGS_MANAGE],
  Audit: [PERMISSIONS.AUDIT_READ],
  "AI Assistant": [PERMISSIONS.AI_READ],
  "Alerts": [PERMISSIONS.ALERTS_READ, PERMISSIONS.ALERTS_MANAGE],
  "QuickBooks": [PERMISSIONS.QUICKBOOKS_READ, PERMISSIONS.QUICKBOOKS_MANAGE],
  "Executive": [PERMISSIONS.EXECUTIVE_READ]
};
